version: '3'
services:
    db:
        build:
            context: docker/db
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        container_name: movies_db
        ports:
            - "3306:3306"
        volumes:
            - .database/db:/var/lib/mysql
        environment:
                MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
                MYSQL_DATABASE: ${MYSQL_DATABASE}
                MYSQL_USER: ${MYSQL_USER}
                MYSQL_PASSWORD: ${MYSQL_PASSWORD}

                HOST_USER: ${HOST_USER}
                HOST_GROUP: ${HOST_GROUP}
                HOST_UID: ${HOST_UID}
                HOST_GID: ${HOST_GID}
        expose:
            - 3306
        networks:
            main:
    php:
        container_name: movies_php
        build:
            context: .
            dockerfile: docker/php/ubuntu.Dockerfile
            args:
                HOST_USER: ${HOST_USER}
                HOST_GROUP: ${HOST_GROUP}
                HOST_UID: ${HOST_UID}
                HOST_GID: ${HOST_GID}
        volumes:
            - ./:/app:rw
        networks:
            - main
        user: ${HOST_USER}
    nginx:
        container_name: movies_nginx
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./:/app:rw
        ports:
            - 80:80
        networks:
            - main

networks:
    main:
